/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quiz.telas;

/**
 *
 * @author 823159187
 */
import com.mycompany.quiz.Noticia;
import com.mycompany.quiz.daos.NoticiaDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class GerenciamentoNoticiasTela extends javax.swing.JFrame {

    /**
     * Creates new form GerenciamentoNoticiasTela
     */
    public GerenciamentoNoticiasTela() {
        super("Squizz");
        initComponents();
        buscarNoticias();
        setLocationRelativeTo(null);
    }
    
    private void buscarNoticias(){
        try{
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            noticiasComboBox.setModel(new DefaultComboBoxModel<>(noticias));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
            e.printStackTrace();
        } 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noticiasComboBox = new javax.swing.JComboBox<>();
        txf_titulo = new javax.swing.JTextField();
        txf_resumo = new javax.swing.JTextField();
        txf_url = new javax.swing.JTextField();
        btn_novo = new javax.swing.JButton();
        btn_atualizar = new javax.swing.JButton();
        btn_remover = new javax.swing.JButton();
        btn_voltar = new javax.swing.JButton();
        btn_limpar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        noticiasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticiasComboBoxActionPerformed(evt);
            }
        });

        txf_titulo.setText("Adicione um Titulo");

        txf_resumo.setText("Adicione um resumo");

        txf_url.setText("Adicione a url");

        btn_novo.setText("Novo");
        btn_novo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_novoActionPerformed(evt);
            }
        });

        btn_atualizar.setText("Atualizar");
        btn_atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_atualizarActionPerformed(evt);
            }
        });

        btn_remover.setText("Remover");
        btn_remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removerActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        btn_limpar.setText("Limpar");
        btn_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_limparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noticiasComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txf_titulo)
                    .addComponent(txf_resumo)
                    .addComponent(txf_url)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_novo)
                        .addGap(33, 33, 33)
                        .addComponent(btn_atualizar)
                        .addGap(18, 18, 18)
                        .addComponent(btn_remover)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addComponent(btn_voltar)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_limpar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noticiasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(txf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(txf_resumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_novo)
                    .addComponent(btn_atualizar)
                    .addComponent(btn_remover)
                    .addComponent(btn_voltar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_limpar)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noticiasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticiasComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            int posicao = noticiasComboBox.getSelectedIndex();
            String titulo = noticias[posicao].getTitulo();
            String resumo = noticias[posicao].getResumo();
            String url = noticias[posicao].getUrl();
            
            txf_titulo.setText(titulo);
            txf_resumo.setText(resumo);
            txf_url.setText(url);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_noticiasComboBoxActionPerformed

    private void btn_novoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_novoActionPerformed
        // TODO add your handling code here:
        try{
            String titulo = txf_titulo.getText();
            String resumo = txf_resumo.getText();
            String url = txf_url.getText();
            Noticia noticia = new Noticia(titulo, resumo, url);
            NoticiaDAO dao = new NoticiaDAO();
            dao.criaNoticia(noticia);
            JOptionPane.showMessageDialog(null, "Noticia criada com sucesso!");
            txf_titulo.setText("");
            txf_resumo.setText("");
            txf_url.setText("");
            buscarNoticias();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos");
            e.printStackTrace();
        }    
    }//GEN-LAST:event_btn_novoActionPerformed

    private void btn_atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_atualizarActionPerformed
        // TODO add your handling code here:
        try {
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            int posicao = noticiasComboBox.getSelectedIndex();
            String titulo = txf_titulo.getText();
            String resumo = txf_resumo.getText();
            String url = txf_url.getText();
            noticias[posicao].setTitulo(titulo);
            noticias[posicao].setResumo(resumo);
            noticias[posicao].setUrl(url);
            dao.atualizaNoticia(noticias[posicao]);
            JOptionPane.showMessageDialog(null, "Noticia atualizada com sucesso");
            buscarNoticias();
           
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Problemas técnicos volte mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_atualizarActionPerformed

    private void btn_removerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removerActionPerformed
        // TODO add your handling code here:
        try {
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            int posicao = noticiasComboBox.getSelectedIndex();
            dao.deletaNoticia(noticias[posicao]);
            JOptionPane.showMessageDialog(null, "Noticia excluida com sucesso");
            txf_titulo.setText("");
            txf_resumo.setText("");
            txf_url.setText("");
            buscarNoticias();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,"Problemas técnicos tente novamente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_removerActionPerformed

    private void btn_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_limparActionPerformed
        // TODO add your handling code here:
        txf_titulo.setText("");
        txf_resumo.setText("");
        txf_url.setText("");
    }//GEN-LAST:event_btn_limparActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        GerenciamentoTela gt = new GerenciamentoTela();
        gt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoNoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoNoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoNoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciamentoNoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciamentoNoticiasTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_atualizar;
    private javax.swing.JButton btn_limpar;
    private javax.swing.JButton btn_novo;
    private javax.swing.JButton btn_remover;
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<Noticia> noticiasComboBox;
    private javax.swing.JTextField txf_resumo;
    private javax.swing.JTextField txf_titulo;
    private javax.swing.JTextField txf_url;
    // End of variables declaration//GEN-END:variables
}
