/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.quiz.telas;

/**
 *
 * @author mathe
 */
import com.mycompany.quiz.models.Sessao;
import com.mycompany.quiz.models.Usuario;
import com.mycompany.quiz.daos.UsuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class MenuJogoTela extends javax.swing.JFrame {

    /**
     * Creates new form MenuJogoTela
     */
    public MenuJogoTela() {
        super("Squizz");
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btn_conta = new javax.swing.JButton();
        btn_jogar = new javax.swing.JButton();
        btn_gerenciamento = new javax.swing.JButton();
        btn_noticia = new javax.swing.JButton();
        btn_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        btn_conta.setBackground(new java.awt.Color(51, 0, 204));
        btn_conta.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btn_conta.setForeground(new java.awt.Color(255, 255, 255));
        btn_conta.setText("Conta");
        btn_conta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_contaActionPerformed(evt);
            }
        });

        btn_jogar.setBackground(new java.awt.Color(51, 0, 204));
        btn_jogar.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btn_jogar.setForeground(new java.awt.Color(255, 255, 255));
        btn_jogar.setText("Jogar");
        btn_jogar.setAutoscrolls(true);
        btn_jogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_jogarActionPerformed(evt);
            }
        });

        btn_gerenciamento.setBackground(new java.awt.Color(51, 0, 204));
        btn_gerenciamento.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btn_gerenciamento.setForeground(new java.awt.Color(255, 255, 255));
        btn_gerenciamento.setText("Gerenciamento");
        btn_gerenciamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gerenciamentoActionPerformed(evt);
            }
        });

        btn_noticia.setBackground(new java.awt.Color(51, 0, 204));
        btn_noticia.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btn_noticia.setForeground(new java.awt.Color(255, 255, 255));
        btn_noticia.setText("Noticias");
        btn_noticia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_noticiaActionPerformed(evt);
            }
        });

        btn_sair.setBackground(new java.awt.Color(255, 0, 51));
        btn_sair.setFont(new java.awt.Font("MS UI Gothic", 1, 12)); // NOI18N
        btn_sair.setForeground(new java.awt.Color(255, 255, 255));
        btn_sair.setText("Sair");
        btn_sair.setAutoscrolls(true);
        btn_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(btn_jogar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_gerenciamento, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                                .addComponent(btn_noticia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(139, 139, 139)
                        .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(130, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(btn_jogar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addComponent(btn_noticia, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_gerenciamento, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_conta, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btn_sair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sairActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_sairActionPerformed

    private void btn_gerenciamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gerenciamentoActionPerformed
        // TODO add your handling code here:
        Usuario usuarios = new Usuario();
        UsuarioDAO dao = new UsuarioDAO();
        Sessao sessao = Sessao.getInstance();
        String nome = sessao.getNomeLogin();
        usuarios.setNome(nome);
        try{
            String email = dao.getEmailUser(usuarios);
            if(email.equals("administrador@squizz.com")){
                GerenciamentoTela gt = new GerenciamentoTela();
                gt.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(null, "Você não tem acesso...");
            }
        }catch(SQLException u){
            throw new RuntimeException(u);
        } catch (Exception ex) {
            Logger.getLogger(MenuJogoTela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_gerenciamentoActionPerformed

    private void btn_contaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_contaActionPerformed
        // TODO add your handling code here:
        ContaTela ct = new ContaTela();
        ct.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_contaActionPerformed

    private void btn_jogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_jogarActionPerformed
        // TODO add your handling code here:
        MenssagemTela mt = new MenssagemTela();
        mt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_jogarActionPerformed

    private void btn_noticiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_noticiaActionPerformed
        // TODO add your handling code here:
        NoticiasTela nt = new NoticiasTela();
        nt.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_noticiaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuJogoTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuJogoTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_conta;
    private javax.swing.JButton btn_gerenciamento;
    private javax.swing.JButton btn_jogar;
    private javax.swing.JButton btn_noticia;
    private javax.swing.JButton btn_sair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
