/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.quiz.telas;

/**
 *
 * @author 823159187
 */
import com.mycompany.quiz.Noticia;
import com.mycompany.quiz.daos.NoticiaDAO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

public class NoticiasTela extends javax.swing.JFrame {

    /**
     * Creates new form NoticiasTela
     */
    public NoticiasTela() {
        super("Squizz");
        initComponents();
        buscarNoticias();
        setLocationRelativeTo(null);
    }
    
    private void buscarNoticias(){
        try{
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            noticiasComboBox.setModel(new DefaultComboBoxModel<>(noticias));
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tente novamente mais tarde");
            e.printStackTrace();
        } 
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        noticiasComboBox = new javax.swing.JComboBox<>();
        btn_voltar = new javax.swing.JButton();
        txf_titulo = new javax.swing.JTextField();
        txf_resumo = new javax.swing.JTextField();
        txf_url = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        noticiasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noticiasComboBoxActionPerformed(evt);
            }
        });

        btn_voltar.setText("Voltar");
        btn_voltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_voltarActionPerformed(evt);
            }
        });

        txf_titulo.setEditable(false);
        txf_titulo.setBorder(javax.swing.BorderFactory.createTitledBorder("Titulo"));

        txf_resumo.setEditable(false);
        txf_resumo.setBorder(javax.swing.BorderFactory.createTitledBorder("Resumo"));

        txf_url.setEditable(false);
        txf_url.setBorder(javax.swing.BorderFactory.createTitledBorder("Url"));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(noticiasComboBox, 0, 380, Short.MAX_VALUE)
                    .addComponent(txf_titulo)
                    .addComponent(txf_resumo)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_voltar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(txf_url))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(noticiasComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(txf_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(txf_resumo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txf_url, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(btn_voltar)
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void noticiasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noticiasComboBoxActionPerformed
        // TODO add your handling code here:
        try{
            NoticiaDAO dao = new NoticiaDAO();
            Noticia [] noticias = dao.obterNoticias();
            int posicao = noticiasComboBox.getSelectedIndex();
            String titulo = noticias[posicao].getTitulo();
            String resumo = noticias[posicao].getResumo();
            String url = noticias[posicao].getUrl();
            
            txf_titulo.setText(titulo);
            txf_resumo.setText(resumo);
            txf_url.setText(url);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Tente mais tarde");
            e.printStackTrace();
        }
    }//GEN-LAST:event_noticiasComboBoxActionPerformed

    private void btn_voltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_voltarActionPerformed
        // TODO add your handling code here:
        MenuJogoTela mj = new MenuJogoTela();
        mj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_voltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NoticiasTela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NoticiasTela().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_voltar;
    private javax.swing.JComboBox<Noticia> noticiasComboBox;
    private javax.swing.JTextField txf_resumo;
    private javax.swing.JTextField txf_titulo;
    private javax.swing.JTextField txf_url;
    // End of variables declaration//GEN-END:variables
}
